# basic
title: Arendaja blogi
subtitle: Kohustuslik lugemine igale programmeerijale
favicon: favicon.ico

# avatar: images/avatar.png
# banner_small: images/banner-small.png
# banner_large: images/banner-large.png
avatar: http://7xrcp8.com1.z0.glb.clouddn.com/avatar.png
banner_small: img/header.jpeg
banner_large: img/header.jpeg

# disqus
disqus_shortname: arendaja

# social
social:
  github: https://github.com/DrakeLeung
  twitter: https://twitter.com/DrakeLeung
  weibo: http://weibo.com/cha12chalyc

# nav #
nav:
  Avaleht: .
  Arhiiv: archives
  Kirjuta: kirjuta
  rss: atom.xml

# heox-renderre-sass
node_sass:
  outputStyle: nested
  precision: 5
  sourceComments: false


google_analytics:  UA-20618536-11
